### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/bspline-fortran#18]
Are their any opportunities to speed up the low-level routines perhaps by using OpenMP, or maybe `do concurrent` loops? Look into this.

**Comment by danhar** [comment]
My (very personal and incomplete) view: last time I looked into `do concurrent`---about two years ago---compiler implementations seemed to be very inefficient. Regarding OpenMP, that may result in unintended nested OpenMP loops: I don't think one can (easily) activate only one of several nested OpenMP constructs. Also, OpenMP has a non-negligible overhead and communication cost and is (in my experience) best used on a level requiring as little thread syncronization as possible. Eg, the outermost of several nested do loops is parallelized with OpenMP.

**Comment by szaghi** [comment]
@jacobwilliams @danhar 

I agree with @danhar . The parallelization is a *noble* aim, but not so trivial when dealing with OpenMP & Co. (that seems an unexpected statement because OpenMP is supposed to be the *simplest* parallel paradigm). I have no experience with *do concurrent*, but I totally agree with @danhar about OpenMP. The actual speedup is not so obvious to predict. How *large* is the parallelizable low-level counts? Are the communication overheads negligible in the *production* usage? As @danhar pointed out, the base-line OpenMP approach is to parallelize the outermost index: even if more *advanced* strategies are possible, e.g. collapse indexes, in my experience it could be a nightmare to enable high speedup. One of the crucial point I found recently is to take much care on the actual *vectorization*: purity and other compiler-optimizer helpers should flavor the occurrences of vectorized codes. Anyhow, I think that this improvement (parallelize bspline) is very interesting! Good work Jacob, as always :clap:

**Comment by danhar** [comment]
Just a short clarification: what I meant with 'unintended' nested OpenMP constructs is the following: in my case, I have parallelized my own code on the outermost loop. The innermost loop calls bspline. If bspline had its own OpenMP construct, then each thread of my own team would create additional private threads in the bspline. That may actually slow down performance, e.g. if the number of threads in my team = number of available cores. Unintended was meant to convey that bspline may often be used as a black box.

**Comment by szaghi** [comment]
@danhar I agree, this is a very good point.

**Comment by jacobwilliams** [comment]
Fair enough. I'll leave as is for now.
