### ISSUE TITLE
array temporary created

### ISSUE THREAD

**Issue by danhar** [jacobwilliams/bspline-fortran#5]
In the call to subroutine check(s,n,k,x,t,ierrs,error), array temporaries are created, which means that actual arguments are copied into temporary storage before routine calls. This may be specific to the Intel Fortran Compiler, and can be seen by building and running with the flag '-check arg_temp_created'. Since this happens for every call to db*val, I was concerned about an adverse performance impact, and started a thread on comp.lang.fortran:

https://groups.google.com/forum/#!topic/comp.lang.fortran/jPRslnUD-Pk

The upshot of that discussion is that:
- This behavior may be specific to Intel Compilers (including the latest).
- The performance impact may be negative, but that could be negligibly small.
- For several reasons it is recommended to change the offending variable to have an assumed-shape, i.e., change
```Fortran
    integer,dimension(4),intent(in)
```
to
```Fortran
    integer,dimension(:),intent(in)
```
This resolves the issue.

**Comment by szaghi** [comment]
Hi all,

I have the same experience with Intel compilers (from v10.x+ up to 15.03, I have not yet tested v16). It seems that Intel compiler has some strange logic to decide when create (or not) a temporary copy. However, the best-practice suggested by Richard Maine and other Guru solves perfectly this Intel issue: it is better to adopt assumed-shape definitions ubiquitously unless there are other specifications that do not permit this.

I like just to report a more detailed hint. When using assumed-shape with both lower and upper bound omitted, the compiler is implicitly reordering the array using 1 as lower bound, this means that

```fortran
call foo(x=x(-3:1))
...
! inside foo
real function foo(x)
real :: x(:) 
! now x is x[1:5] and not [-3:1]
```

In the case of bspline I think this is not a matter because `dimension(4)` is identical to `dimension(1:4)`, but I always prefer to be explicit thus I suggest to use `integer, dimension(1:), intent(in)`.

My best regards.

**Comment by jacobwilliams** [comment]
Thanks! I committed this change to the `thread-safe` branch. Will merge with `master` after I do some more testing.
